In [ ]:
import pandas as pd

In [ ]:
prodi_df = pd.read_csv("/content/dataset_cleaned.csv")
prodi_df.head()

,No,Nama Prodi,Nama PT,Jenjang
0,1,ADMINISTRASI RUMAH SAKIT,AKADEMI ADMINISTRASI RUMAH SAKIT MATARAM,D-III
1,2,Akuntansi,Akademi Akuntansi (AKTAN) Boekittinggi,D-III
2,3,Akuntansi,Akademi Akuntansi Bandung,D-III
3,4,Akuntansi,Akademi Akuntansi Bina Insani,D-III
4,5,Akuntansi,Akademi Akuntansi Borobudur,D-III

In [ ]:
print("Data awal:")
print(prodi_df.head())

Data awal:
   No                Nama Prodi                                   Nama PT  \
0   1  ADMINISTRASI RUMAH SAKIT  AKADEMI ADMINISTRASI RUMAH SAKIT MATARAM
1   2                 Akuntansi    Akademi Akuntansi (AKTAN) Boekittinggi
2   3                 Akuntansi                 Akademi Akuntansi Bandung
3   4                 Akuntansi             Akademi Akuntansi Bina Insani
4   5                 Akuntansi               Akademi Akuntansi Borobudur

  Jenjang
0   D-III
1   D-III
2   D-III
3   D-III
4   D-III

In [ ]:
prodi_df = prodi_df.loc[:, ~prodi_df.columns.str.contains('Unnamed')]

In [ ]:
prodi_df = prodi_df.dropna(subset=['No', 'Nama Prodi', 'Nama PT', 'Jenjang'])

In [ ]:
prodi_df_s1 = prodi_df[prodi_df['Jenjang'].str.strip().str.upper() == 'S1']

In [ ]:
prodi_df_s1.loc[:, 'Nama Prodi'] = prodi_df_s1['Nama Prodi'].str.strip()
prodi_df_s1.loc[:, 'Nama PT'] = prodi_df_s1['Nama PT'].str.strip()
prodi_df_s1.loc[:, 'Jenjang'] = prodi_df_s1['Jenjang'].str.strip()

In [ ]:
print("\nData setelah pembersihan (khusus S1):")
print(prodi_df_s1.head())

Data setelah pembersihan (khusus S1):
      No                                   Nama Prodi  \
907  908          Pendidikan Guru Madrasah Ibtidaiyah
908  909                              Ekonomi Syariah
909  910  Hukum Keluarga Islam (Ahwal Al Syakhshiyah)
910  911             Hukum Ekonomi Syariah (Muamalah)
911  912                           Pendidikan Biologi

                          Nama PT Jenjang
907  IAI Agus Salim Metro Lampung      S1
908  IAI Agus Salim Metro Lampung      S1
909  IAI Agus Salim Metro Lampung      S1
910                    IAIN Ambon      S1
911                    IAIN Ambon      S1

In [ ]:
prodi_df = prodi_df[(prodi_df['Jenjang'] != 'S3')]
prodi_df.head()

,No,Nama Prodi,Nama PT,Jenjang
0,1,ADMINISTRASI RUMAH SAKIT,AKADEMI ADMINISTRASI RUMAH SAKIT MATARAM,D-III
1,2,Akuntansi,Akademi Akuntansi (AKTAN) Boekittinggi,D-III
2,3,Akuntansi,Akademi Akuntansi Bandung,D-III
3,4,Akuntansi,Akademi Akuntansi Bina Insani,D-III
4,5,Akuntansi,Akademi Akuntansi Borobudur,D-III

In [ ]:
print(prodi_df.shape)

(18798, 4)

In [ ]:
prodi_df.isna().sum()

No            0
Nama Prodi    0
Nama PT       0
Jenjang       0
dtype: int64

In [ ]:
print("Jumlah duplikasi data = ", prodi_df.duplicated().sum())

Jumlah duplikasi data =  0

In [ ]:
prodi_df.to_csv('dataset_cleaned_fix.csv', index=False)